mylist = [
    "Afghanistan",
    "Albania",
    "Argentina",
    "Australia",
    "Austria",
    "Bangladesh",
    "Belarus",
    "Belgium",
    "Bolivia",
    "Bosnia & Herzegovina",
    "Brazil",
    "Cameroon",
    "Canada",
    "Chile",
    "China",
    "Colombia",
    "Croatia",
    "Cuba",
    "Czechia",
    "Denmark",
    "Ecuador",
    "Egypt",
    "Estonia",
    "Finland",
    "France",
    "Gambia",
    "Georgia",
    "Germany",
    "Greece",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Japan",
    "Kenya",
    "Latvia",
    "Lebanon",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Mexico",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Netherlands",
    "New Zealand",
    "Nigeria",
    "Norway",
    "Pakistan",
    "Paraguay",
    "Peru",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Saudi Arabia",
    "Serbia",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "South Africa",
    "South Korea",
    "Spain",
    "Sweden",
    "Switzerland",
    "Thailand",
    "Tunisia",
    "Turkey",
    "Ukraine",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Venezuela",
]
